name: Deploy
on:
  workflow_dispatch:
    inputs:
      example_name:
        description: 'Name of the example to deploy'
        required: true

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/TerraformCiRole
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Terraform
        env:
          GIT_COMMIT: ${{ github.sha }}
        run: |
          cd examples/${{ inputs.example_name }}
          terraform --version
          terraform init
          # Detect whether launched example defines variable "git_commit"
          if terraform providers schema -json | jq -e '.schema.terraform.variables | has("git_commit")' >/dev/null 2>&1; then
            echo "Passing git_commit variable..."
            VAR_ARGS="-var git_commit=$GIT_COMMIT"
          else
            echo "No git_commit variable in this example."
            VAR_ARGS=""
          fi
          terraform plan $VAR_ARGS
          terraform apply -auto-approve $VAR_ARGS

